name: Deploy to Pantheon
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.19.1
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
      run: |
        git config user.email "barry.meehan@pantheon.io"
        git config user.name "Barry Meehan"
        git remote add pantheon $pantheon_repo
        git fetch pantheon master
        git merge pantheon/master --allow-unrelated-histories
        rm .gitignore
        composer install
        git add -f .
        git commit -nam 'Commit all files'
        git push -f pantheon HEAD:master
